sudo: false
dist: trusty

language: php

notifications:
  email: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

# Todo: Run on PHP 5.2-5.6 as well.
php:
  - 7.2
  - 7.0
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=nightly WP_MULTISITE=0
  - WP_VERSION=nightly WP_MULTISITE=1

matrix:
  include:
  - php: 5.2
    env: WP_VERSION=latest WP_MULTISITE=0
    dist: precise

before_install:
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      cp $HOME/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini /tmp
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi

install:
  - composer install
  - |
    # Install the specified version of PHPUnit depending on the PHP version:
    case "$TRAVIS_PHP_VERSION" in
      7.2|7.1|7.0|nightly)
        echo "Using PHPUnit 6.x"
        travis_retry composer require "phpunit/phpunit:^6"
        ;;
      5.6|5.5|5.4|5.3)
        echo "Using PHPUnit 4.x"
        travis_retry composer require "phpunit/phpunit:^4"
        ;;
      5.2)
        # Do nothing, use default PHPUnit 3.6.x
        echo "Using default PHPUnit, hopefully 3.6"
        ;;
      *)
        echo "No PHPUnit version handling for PHP version $TRAVIS_PHP_VERSION"
        exit 1
        ;;
    esac

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: composer test

jobs:
  fast_finish: true
  include:
    - stage: lint
      script:
        - composer lint
    - stage: coverage
      before_install: skip
      script:
        - composer test -- --coverage-clover=coverage.xml
      after_script:
        - bash <(curl -s https://codecov.io/bash)

stages:
  - lint
  - test
  - coverage
  - deploy
